pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bash 'Jenkins/build.sh'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
