pipeline {
    agent any
    
    environment {
        PASS = credentials('DockerHubPass')
    }

    stages {
        stage('Build') {
            steps {
                bat './Jenkins/Build/build.bat'
            }
        }
        stage('Push') {
            steps {
                bat './Jenkins/Push/push.bat'
            }
        }
        stage('Clean') {
            steps {
                bat './Jenkins/Clean/clean.bat'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
